### ISSUE TITLE
Getting error while installing through composer require rafaeltovar/php-tus-aws-s3

### ISSUE THREAD

**Issue by devanddhiraj** [rafaeltovar/php-tus-aws-s3#3]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install rafaeltovar/php-tus-aws-s3 v1.0.5
    - Conclusion: don't install rafaeltovar/php-tus-aws-s3 v1.0.4
    - Conclusion: don't install rafaeltovar/php-tus-aws-s3 v1.0.3
    - Conclusion: don't install rafaeltovar/php-tus-aws-s3 v1.0.2
    - Conclusion: don't install rafaeltovar/php-tus-aws-s3 v1.0.1
    - Conclusion: remove guzzlehttp/guzzle 7.3.0
    - Installation request for rafaeltovar/php-tus-aws-s3 ^1.0 -> satisfiable by rafaeltovar/php-tus-aws-s3[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5].
    - Conclusion: don't install guzzlehttp/guzzle 7.3.0
    - rafaeltovar/php-tus-aws-s3 v1.0.0 requires guzzlehttp/guzzle ^6.4 -> satisfiable by guzzlehttp/guzzle[6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.3.0].
    - Installation request for guzzlehttp/guzzle (locked at 7.3.0) -> satisfiable by guzzlehttp/guzzle[7.3.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by rafaeltovar** [comment]
Sorry, I can't continue maintaining the project. Please use the original project to perform the same functionality. 

https://github.com/rafaeltovar/php-tus-aws-s3/blob/main/notes-about-tus-aws-s3.md
